#!/usr/bin/env python3
import sys
import os


def embed_dll_to_header(dll_path, header_path):
    """将DLL文件转换为C++头文件"""
    with open(dll_path, 'rb') as f:
        dll_data = f.read()
    
    # 获取DLL文件名（不含扩展名）
    dll_name = os.path.splitext(os.path.basename(dll_path))[0]
    # 将文件名中的点号替换为下划线，确保是有效的C++标识符
    dll_name = dll_name.replace('.', '_')
    # 生成变量名
    var_name_data = 'g_' + dll_name + 'Data'
    var_name_size = 'g_' + dll_name + 'Size'
    
    with open(header_path, 'w') as f:
        f.write('#pragma once\n\n')
        f.write('// ' + dll_name + '.dll binary data\n')
        f.write('// This file is auto-generated by embed_dll.py\n\n')
        f.write('const unsigned char ' + var_name_data + '[] = {\n')
        
        # 每行写16个字节
        for i in range(0, len(dll_data), 16):
            line_data = dll_data[i:i+16]
            hex_strings = []
            for byte in line_data:
                hex_strings.append('0x{:02x}'.format(byte))
            line = '    ' + ', '.join(hex_strings) + ','
            f.write(line + '\n')
        
        f.write('};\n')
        f.write('const size_t ' + var_name_size + ' = ' + str(len(dll_data)) + ';\n\n')


if __name__ == '__main__':
    if len(sys.argv) != 3:
        print('Usage: ' + sys.argv[0] + ' <dll_path> <header_path>')
        sys.exit(1)
    
    dll_path = sys.argv[1]
    header_path = sys.argv[2]
    
    if not os.path.exists(dll_path):
        print('Error: DLL file \'' + dll_path + '\' not found')
        sys.exit(1)
    
    embed_dll_to_header(dll_path, header_path)
    print('Successfully embedded ' + dll_path + ' into ' + header_path)